pipeline {
    agent any

    tools {
        maven 'M3' // Asegúrate de tener Maven configurado como 'M3' en Jenkins
    }

    stages {
        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Package') {
            steps {
                bat 'mvn package'
            }
        }
    }
}
